spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krishnaramachandran1973/todo-configurations.git
          search-paths:          - main
server:  port: 8888          